spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springdevinentorydb
    username: springdevuser
    password: springdevpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        type: TRACE
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true